Cilekotha/App_Login/urls.py
from django.urls import path

from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/', views.log_in, name='log_in'),
    path('logout/', views.log_out, name='log_out'),
    path('change-profile/', views.change_profile, name='change_profile')
]

Cilekotha/App_Order/urls.py
from django.urls import path
from . import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="cart"),
    path('cart/', views.view_cart, name="view_cart"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase-quantity/<pk>/', views.increase_quantity, name="increase_quantity"),
    path('decrease-quantity/<pk>/', views.decrease_quanity, name="decrease_quantity"),
]

Cilekotha/App_Payment/urls.py
from django.urls import path
from . import views

app_name = 'App_Payment'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('status/', views.status, name='status'),
    path('payment-status', views.payment_status, name='payment_status'),
    path('purchased/<val_id>/<tran_id>/', views.purchased_order, name='purchased_order'),
    path('order/', views.order_view, name='order_view')
]

Cilekotha/App_Shop/urls.py
from django.urls import path

from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('product/<pk>', views.ProductDetail.as_view(), name="product"),
]

Cilekotha/Cilekotha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cilekotha/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/dd13a9194f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href={% static 'css/main.css' %}>
    <title>{% block title_block %} E-com | Cilekotha {% endblock %}</title>
    <style>
      .card {
        height: 350px;;
      }
      .card-product:after {
        content: "";
        display: table;
        clear: both;
        visibility: hidden;
      }
      .card-product .price_new, .card-product .price {
        margin-right: 5px;
      }
      .card-product .price-old {
        color: #999;
      }
      .card-product .img-wrap {
        border-radius: 3px 3px 0 0;
        overflow: hidden;
        position: relative;
        height: 220px;
        text-align: center;
      }
      .card-product .img-wrap img {
        max-height: 100%;
        max-width: 100%;
        object-fit: cover;
      }
      .card-product .info-wrap {
        overflow: hidden;
        padding: 15px;
        border-top: 1px solid #eee;
      }
      .card-product .action-wrap {
        padding-top: 4px;
        margin-top: 4px;
      }

      .card-product .bottom-wrap {
        padding: 15px;
        border-top: 1px solid #eee;
      }
      .card-product .title {
        margin-top: 0px;
      }


    </style>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
      <!-- show messages -->
      <div class="messages container mt-2">
        {% if messages %}
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
          {{message}}
          <button type="submit" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
        </div>
        {% endfor %}
        {% endif %}
      </div>
        {% block body_block %}

        {% endblock %}

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

Cilekotha/templates/navbar.html
{% load custom_filter %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container">
  <a class="navbar-brand" href={% url 'App_Shop:home' %}>Cilekotha</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  {% if request.user.is_authenticated %}
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href={% url 'App_Order:view_cart' %}>
          <i class="fas fa-shopping-cart"></i> Cart
          <span class="badge badge-light">{{ request.user | cart_count }}</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ request.user.profile.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href={% url 'App_Login:change_profile' %}>Profile</a>
          <a class="dropdown-item" href={% url 'App_Payment:order_view' %}>Orders</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href={% url 'App_Login:log_out' %}>Logout</a>
        </div>
      </li>
    </ul>

  </div>
  {% else %}
    <li class="nav-link active">
      <a class="nav-link" href={% url 'App_Login:log_in' %}>Login</a>
    </li>
  {% endif %}
</div>
</nav>