Cilekotha/App_Order/urls.py
from django.urls import path
from . import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="cart"),
    path('cart/', views.view_cart, name="view_cart"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase-quantity/<pk>/', views.increase_quantity, name="increase_quantity"),
    path('decrease-quantity/<pk>/', views.decrease_quanity, name="decrease_quantity"),
]

Cilekotha/App_Shop/urls.py
from django.urls import path

from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('product/<pk>', views.ProductDetail.as_view(), name="product"),
]

Cilekotha/Cilekotha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cilekotha/App_Shop/models.py
from distutils.archive_util import make_zipfile
from unicodedata import category
from django.db import models

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Categories'

class Product(models.Model):
    main_image = models.ImageField(upload_to='product')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE)
    preview_text = models.TextField(max_length=300, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created']

Cilekotha/App_Shop/views.py
from django.views.generic import ListView ,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from App_Shop.models import Product

# Create your views here.
class Home(ListView):
    model = Product
    template_name = 'App_Shop/home.html'

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'App_Shop/product_detail.html'

Cilekotha/templates/App_Shop/home.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
    <h2 class="my-5">Featured Products</h2>
    <div class="row">
        {% for product in object_list %}
        <div class="col-md-6 col-sm-12 col-lg-3">
            <figure class="card card-product">
                <div class="img-wrap">
                    <img src="/media/{{product.main_image}}" style="width: 100%; height:300px;">
                </div>
                <figcaption class="info-wrap">
                    <h6 class="title"><a href={% url 'App_Shop:product' product.pk %}>{{ product.name }}</a></h6>
                    <div class="action-wrap">
                        <div class="price-wrap h5">
                            <span class="price-new">&#2547; {{ product.price }}</span>
                            <span class="price-old"><strike>&#2547; {{ product.old_price }}</strike></span>
                        </div>
                    </div>
                </figcaption>
            </figure>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Cilekotha/templates/App_Shop/product_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="contianer my-5">
    <div class="card">
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div>
                            <a href=""><img src="/media/{{ object.main_image }}" style="width:450px"></a>
                        </div>
                    </div>
                </article>
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mp-3">{{ object.name }}</h3>
                    <p class="price-detail-wrap">
                        <span class="price h3 text-warning">
                            <span class="currency">BDT &#2547;</span><span class="num">{{ object.price }}</span>
                        </span>
                    </p>
                    <dl class="item-property">
                        <dt></dt>
                        <dd>
                            <p>{{ object.detail_text|linebreaks }}</p>
                        </dd>
                    </dl>
                    <a href={% url 'App_Order:cart' object.pk %} class="btn btn-lg btn-outline-primary text-uppercase"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
                </article>
            </aside>
        </div>
    </div>
</div>
{% endblock %}