Cilekotha/App_Order/urls.py
from django.urls import path
from . import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="cart"),
    path('cart/', views.view_cart, name="view_cart"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('increase-quantity/<pk>/', views.increase_quantity, name="increase_quantity"),
    path('decrease-quantity/<pk>/', views.decrease_quanity, name="decrease_quantity"),
]

Cilekotha/App_Payment/urls.py
from django.urls import path
from . import views

app_name = 'App_Payment'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('status/', views.status, name='status'),
    path('payment-status', views.payment_status, name='payment_status'),
    path('purchased/<val_id>/<tran_id>/', views.purchased_order, name='purchased_order'),
    path('order/', views.order_view, name='order_view')
]

Cilekotha/App_Shop/urls.py
from django.urls import path

from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('product/<pk>', views.ProductDetail.as_view(), name="product"),
]

Cilekotha/Cilekotha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cilekotha/App_Order/models.py
from django.db import models
from django.conf import settings

from App_Shop.models import Product

# Create your models here.
class Cart(models.Model):
    item = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='cart')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_cart')
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.quantity} X {self.item.name}'
    
    def get_total(self):
        total = self.quantity * self.item.price
        float_total = format(total, '.2f')
        return float_total

class Order(models.Model):
    order_items = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_order")
    ordered = models.BooleanField(default=False)
    payment_id = models.CharField(max_length=264, blank=True, null=True)
    order_id = models.CharField(max_length=264, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return self.user.email
    
    def total_order(self):
        total = 0
        for order_item in self.order_items.all():
            total += float(order_item.get_total())
        return total

Cilekotha/App_Order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from App_Shop.models import Product
from .models import Cart, Order

# Create your views here.
@login_required
def add_to_cart(request,pk):
    items = get_object_or_404(Product, pk=pk)
    check_cart = Cart.objects.get_or_create(item=items, user=request.user, purchased=False)
    check_user_order = Order.objects.filter(user=request.user, ordered=False)
    add_cart = check_cart[0]
    if check_user_order.exists():
        order = check_user_order[0]
        if order.order_items.filter(item=items).exists():
            add_cart.quantity += 1
            add_cart.save()
            messages.info(request, "This item quantity was update.")
            return redirect('App_Shop:home')
        else:
            order.order_items.add(add_cart)
            messages.info(request, "This item was added to the cart.")
            return redirect('App_Shop:home')
    else:
        add_order = Order(user=request.user, ordered=False)
        add_order.save()
        add_order.order_items.add(add_cart)
        messages.info(request, "Order updated.")
        return redirect('App_Shop:home')

@login_required
def view_cart(request):
    see_cart = Cart.objects.filter(user=request.user, purchased=False)
    see_order =  Order.objects.filter(user=request.user, ordered=False)
    if see_order.exists() and see_cart.exists():
        return render(request, 'App_Order/cart.html', {'see_cart':see_cart, 'see_order':see_order[0]})
    else:
        messages.warning(request, "Your cart is empty.")
        return redirect('App_Shop:home')

@login_required
def remove_from_cart(request,pk):
    item = get_object_or_404(Product, pk=pk)
    remove_cart = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
    remove_order = Order.objects.filter(user=request.user, ordered=False)
    if remove_order.exists():
        r_order = remove_order[0]
        if r_order.order_items.filter(item=item).exists():
            r_order.order_items.remove(remove_cart)
            remove_cart.delete()
            messages.warning(request, f"{item.name} was remove from your cart.")
            return redirect("App_Order:view_cart")
        else:
            messages.info(request, "This item is not in your cart.")
            return redirect("App_Shop:home")
    else:
        messages.info(request, "You didn't do any order yet.")
        return redirect("App_Shop:home")

@login_required
def increase_quantity(request,pk):
    item = get_object_or_404(Product, pk=pk)
    inc_cart = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
    inc_order = Order.objects.filter(user=request.user, ordered=False)

    if inc_order.exists():
        increase_order = inc_order[0]
        if increase_order.order_items.filter(item=item).exists():
            inc_cart.quantity += 1
            inc_cart.save()
            return redirect('App_Order:view_cart')
        else:
            messages.info(request, "This item is not in your cart")
            return redirect('App_Shop:home')
    else:
        messages.warning("You didn't do any order yet.")
        return redirect('App_Shop:home')

@login_required
def decrease_quanity(request,pk):
    item = get_object_or_404(Product, pk=pk)
    dec_cart = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
    dec_order = Order.objects.filter(user=request.user, ordered=False)

    if dec_order.exists():
        decrease_order = dec_order[0]
        if decrease_order.order_items.filter(item=item).exists():
            if dec_cart.quantity > 1:
                dec_cart.quantity -= 1
                dec_cart.save()
                return redirect('App_Order:view_cart')
            else:
                decrease_order.order_items.remove(dec_cart)
                dec_cart.delete()
                return redirect('App_Order:view_cart')
        else:
            messages.info(request, "This item is not in your cart")
            return redirect('App_Shop:home')
    else:
        messages.warning("You didn't do any order yet.")
        return redirect('App_Shop:home')

Cilekotha/templates/App_Order/cart.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
    <div class="my-5">
        <h2>Your Cart</h2>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col" width="15%">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Quantity</th>
                <th scope="col" align="right">Price</th>
                <th scope="col">Remove</th>
            </tr>
        </thead>
        <tbody>
            {% for cart in see_cart %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ cart.item.name }}</td>
                <td>
                    <a class="mr-2" href={% url 'App_Order:decrease_quantity' cart.item.pk %}><span class="badge badge-light"><i class="fas fa-minus"></i></span></a>
                    {{ cart.quantity }}
                    <a class="mr-2" href={% url 'App_Order:increase_quantity' cart.item.pk %}><span class="badge badge-light"><i class="fas fa-plus"></i></span></a>
                </td>
                <td align="right">{{ cart.item.price }}&#2547;</td>
                <td><a class="btn btn-danger btn-sm" href={% url 'App_Order:remove' cart.item.pk %}>Remove to Cart</a></td>
            </tr>
            {% endfor %}
            <tr> 
                <th scope="row"></th>
                <td colspan="2">Total</td>
                <td align="right">{{ see_order.total_order }}&#2547;</td>
                <td></td>
            </tr>
            <tr>
                <th scope="row"></th>
                <td colspan="4" class="text-right">
                    <a  class="btn btn-warning mr-4" href={% url 'App_Shop:home' %}>Continue Shopping</a>
                    <a class="btn btn-success mr-4" href={% url 'App_Payment:checkout' %}>Proceed to Checkout</a>
                </td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}