Cilekotha/App_Payment/urls.py
from django.urls import path
from . import views

app_name = 'App_Payment'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('status/', views.status, name='status'),
    path('payment-status', views.payment_status, name='payment_status'),
    path('purchased/<val_id>/<tran_id>/', views.purchased_order, name='purchased_order'),
    path('order/', views.order_view, name='order_view')
]

Cilekotha/App_Shop/urls.py
from django.urls import path

from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('product/<pk>', views.ProductDetail.as_view(), name="product"),
]

Cilekotha/Cilekotha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cilekotha/App_Payment/models.py
from django.db import models

from django.conf import settings

# Create your models here.
class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="payment")
    address = models.CharField(max_length=264, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    city = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return f"{self.user.profile.username}'s billing address"
    
    def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]

        for field_name in field_names:
            value = getattr(self, field_name)

            if value is None or value == '':
                return False
        return True

    class Meta:
        verbose_name_plural = 'Billing Addresses'

Cilekotha/App_Payment/forms.py
from socket import fromshare
from django import forms

from .models import BillingAddress

class AddressForm(forms.ModelForm):
    template_name = 'App_Payment/billing_address.html'
    class Meta:
        model = BillingAddress
        fields = ['address', 'zipcode', 'city', 'country']

Cilekotha/App_Payment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect

from .models import BillingAddress
from .forms import AddressForm
from App_Order.models import Order, Cart

#payment
from sslcommerz_python.payment import SSLCSession
from decimal import Decimal
import requests
import socket

# Create your views here.
@login_required
def checkout(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)[0]
    form = AddressForm(instance=saved_address)
    if request.method == 'POST':
        form = AddressForm(request.POST, instance=saved_address)
        if form.is_valid():
            form.save()
            messages.success(request, "Shipping address saved.")
            return redirect('App_Payment:checkout')
    view_order = Order.objects.filter(user=request.user, ordered=False)
    total = view_order[0].total_order()
    if view_order.exists():
        orders = view_order[0].order_items.all()
    dict = {'form':form, 'orders':orders, 'total':total, 'saved_address':saved_address}
    return render(request, 'App_Payment/checkout.html', dict)


@login_required
def status(request):
    saved_address = BillingAddress.objects.get_or_create(user=request.user)[0]
    
    if not saved_address.is_fully_filled():
        messages.warning(request, "Please fill up your shipping address.")
        return redirect('App_Payment:checkout')
    
    if not request.user.profile.is_fully_filled():
        messages.warning(request, "Please fill up your profile address.")
        return redirect('App_Login:change_profile')

    store_id = "abc63037a6d8fcc3"
    api_key = "abc63037a6d8fcc3@ssl"
    mypayment = SSLCSession(sslc_is_sandbox=True, sslc_store_id=store_id, sslc_store_pass=api_key)

    status_url = request.build_absolute_uri(reverse("App_Payment:payment_status"))
    mypayment.set_urls(success_url=status_url, fail_url=status_url, cancel_url=status_url, ipn_url=status_url)

    order = Order.objects.filter(user=request.user, ordered=False)[0].order_items.all()
    order_qs = Order.objects.filter(user=request.user, ordered=False)[0]
    # cart = Cart.objects.filter(user=request.user, purchased=False)
    category = order[0].item.category.title
    name = order[0].item.name 

    mypayment.set_product_integration(total_amount=Decimal(order_qs.total_order()), currency='BDT', product_category=category, product_name=name, num_of_item=order.count(), shipping_method='Courier', product_profile='None')

    current_user = request.user.profile
    mypayment.set_customer_info(name=current_user.full_name, email=request.user.email, address1=current_user.address_1, address2=current_user.address_1, city=current_user.city, postcode=current_user.zip_code, country=current_user.country, phone=current_user.phone)

    mypayment.set_shipping_info(shipping_to=current_user.username, address=saved_address.address, city=saved_address.city, postcode=saved_address.zipcode, country=saved_address.country)

    # # If you want to post some additional values
    # mypayment.set_additional_values(value_a=request.user.email, value_b='portalcustomerid', value_c='1234', value_d='uuid')

    response_data = mypayment.init_payment()
    return redirect(response_data['GatewayPageURL'])


@csrf_exempt
def payment_status(request):
    
    if request.method == 'POST' or request.method == 'post':
        payment_state = request.POST

        if payment_state['status'] == 'VALID':
            tran_id = payment_state['tran_id']
            val_id = payment_state['val_id']

            messages.success(request, "Payment successfully completed.")
            return HttpResponseRedirect(reverse('App_Payment:purchased_order', kwargs=({'val_id':val_id, 'tran_id':tran_id})))
        elif payment_state['status'] == 'FAILED':
            messages.warning(request, "Payment not completed successfully. Try again. Note: AUTO REDIRECT AFTER 5 SECONDS.")
        else:
            messages.warning(request, "Payment Cancelled. Try again. Note: AUTO REDIRECT AFTER 5 SECONDS.")

    return render(request, 'App_Payment/payment_status.html')

@login_required
def purchased_order(request,val_id,tran_id):
    order = Order.objects.filter(user=request.user, ordered=False)[0]
    order.order_id = tran_id
    order.payment_id = val_id
    order.ordered = True
    order.save()

    cart = Cart.objects.filter(user=request.user, purchased=False)

    for item in cart:
        item.purchased = True
        item.save()
    
    return redirect('App_Shop:home')

@login_required
def order_view(request):
    try:
        orders = Order.objects.filter(user=request.user, ordered=True)
        dict = {'orders':orders}
    except:
        messages.warning(request, "You don't have an active order.")
    return render(request, 'App_Payment/order.html', dict)

Cilekotha/templates/App_Payment/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container mt-5">
    <h2 class="mb-3">
        Shipping Address > <span class="text-muted">Checkout</span>
    </h2>
    <div class="row">
        <div class="col-md-9">
            <div class="card mb-5" style="height: auto">
                <div class="card-body">
                    <form method="POST">
                        {{ form|crispy }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary float-right">Save Address</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card" style="height:auto">
                <div class="card-body">
                    {% for order in orders %}
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            {{ order.item.name }} <span class="text-muted">X</span> {{ order.quantity }}
                        </li>
                    </ul>
                    {% endfor %}
                </div>
                <div class="card-footer">
                    <b>
                        <span class="float-left">Total</span>
                        <span class="float-right">&#2547; {{ total | floatformat:2 }}</span>
                    </b>
                </div>
            </div>
            <br>
            <br>

            {% if saved_address.is_fully_filled %}
            <a href={% url 'App_Payment:status' %} class="btn btn-warning btn-md">Make Payment</a>
            {% else %}
            <div class="alert alert-info">
                <p>Please complete shipping address!</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

Cilekotha/templates/App_Payment/order.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container mt-5">
    <h2 class="text-center"><strong>Your Order</strong></h2>
    <div class="row">
        <div class="col-md-12">
            <div class="card mt-5" style="height:auto">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Order Id</th>
                                <th scope="col">Products</th>
                                <th scope="col">Status</th>
                            </tr>
                        </thead>
                        {% for order in orders %}
                        <tbody>
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td><a href="">{{ order.order_id }}</a></td>
                                <td>{% for item in order.order_items.all %} {{ item }}<br>{% endfor %}</td>
                                <td><span class="badge badge-primary">Processing your order.</span></td>
                            </tr>
                        </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-12 my-5 text-center">
            <a href=""></a>
        </div>
    </div>
</div>
{% endblock %}

Cilekotha/templates/App_Payment/payment_status.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta http-equiv="refresh" content="5; url={% url 'App_Shop:home' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Payment Status</title>
  </head>
  <body>
    <div class="container">
        <div class="messages container mt-2">
            {% if messages %}
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
              {{message}}
              <button type="submit" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
            </div>
            {% endfor %}
            {% endif %}
          </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>